// Generated by Menu Configurator
#ifndef CONFIGURATOR_HEADFILE_H
#define CONFIGURATOR_HEADFILE_H

#include "zf_common_headfile.h"
#include "zf_device_ips200.h"
#include "UserConfig.h"
#include "BasicGeos.h"
#include "ComplexGraphics.h"
#include "Items.h"
#include "KV_Storage.h"
#include "HID.h"
#include "Menu_Handler.h"

// --- Theme Settings ---
// 主背景色: 深邃、沉稳的海军蓝
#define BackgroundColor                         0x08D5  // RGB565 for #0B192E

// 默认文本颜色: 柔和的灰白色，保证在深色背景上的可读性
#define TextColor                               0xE71C  // RGB565 for #E0E0E0

// 选中项背景色: 明亮的聚焦蓝，用于高亮当前选择
#define Background_Selected_Color               0x1A51  // RGB565 for #1E4A8B

// 选中项文本颜色: 清晰的亮白色，与选中背景形成强烈对比
#define Text_Selected_Color                     0xF79F  // RGB565 for #F0FFFF

// 标题分割线颜色: 稍暗的蓝色，与背景融为一体但仍可辨识
#define TitleSeperatorColor                     0x2A2D  // RGB565 for #2A456B

// 编辑数值时，非活动数字的颜色 (与选中项文本色一致，保持协调)
#define ChangeValueTextColor                    0xF79F  // RGB565 for #F0FFFF

// 编辑数值时，活动数字的颜色 (点睛之笔：珊瑚红，非常醒目)
#define ChangeValueText_Selected_BitColor       0xFCB5  // RGB565 for #FF8C69

// 编辑数值时，活动数字的背景色 (使用默认文本的灰白色，形成反色高亮效果)
#define ChangeValueText_Selected_Background_Color 0xE71C  // RGB565 for #E0E0E0

#define MAX_ITEMS_PER_PAGE                  9

// Add your custom function headers here if needed
// e.g. #include "my_functions.h"

// --- Menu Entry Point ---
// The following should be your root menu struct.
// You will call EnterMenu(&MainMenu); to start.
extern Menu MainMenu;

// Call this function once at startup to initialize all menus.
void InitializeAllMenus(void);

#endif // CONFIGURATOR_HEADFILE_H