// Generated by Menu Configurator
#ifndef CONFIGURATOR_HEADFILE_H
#define CONFIGURATOR_HEADFILE_H

#include "zf_common_headfile.h"
#include "zf_device_ips200.h"
#include "UserConfig.h"
#include "Theme.h"
#include "BasicGeos.h"
#include "ComplexGraphics.h"
#include "Items.h"
#include "KV_Storage.h"
#include "HID.h"
#include "Menu_Handler.h"

// Add your custom function headers here if needed
// e.g. #include "my_functions.h"

// --- Menu Entry Point ---
// The following should be your root menu struct.
// You will call EnterMenu(&MainMenu); to start.
extern Menu MainMenu;

// Call this function once at startup to initialize all menus.
void InitializeAllMenus(void);

#endif // CONFIGURATOR_HEADFILE_H