// Generated by Menu Configurator

#ifndef THEME_H
#define THEME_H

#include "zf_common_headfile.h"

#define TextColor RGB565_WHITE
#define Text_Selected_Color RGB565_BLUE
#define BackgroundColor RGB565_BLACK
#define Background_Selected_Color RGB565_GRAY
#define TitleSeperatorColor RGB565_GRAY
#define ChangeValueTextColor RGB565_GREEN
#define ChangeValueText_Selected_BitColor RGB565_YELLOW
#define ChangeValueText_Selected_Background_Color RGB565_BLUE
#define MAX_ITEMS_PER_PAGE 9

#endif // THEME_H